name: build_docker_image

on:
  workflow_dispatch:
  

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: creation de l'image
      run: docker build -t tweeter .
      working-directory: Projet